# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/finflow?sslmode=disable
    username: finflow
    password: finflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create   # use update to create missing tables on first run
    properties:
      hibernate.format_sql: true
